language: python
python:
  - "3.6"

branches:
  only:
    - "master"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
script:
  - flake8
after_success:
  - python deploy.py

cache: pip

notifications:
  email: false
